//! Built-in substrings that mark a process as "dev" for the DEV Processes tab.
//!
//! Matching is case-insensitive substring search over `name + cmdline`.
//! Keep markers specific enough to avoid obvious false positives when possible;
//! users can extend via `extra_dev_markers` in config.

pub const DEV_MARKERS: &[&str] = &[
    // Editors / IDEs
    "zed",
    "cursor",
    "code helper",
    "visual studio code",
    "vscode",
    "vscodium",
    "intellij",
    "webstorm",
    "pycharm",
    "goland",
    "clion",
    "phpstorm",
    "rubymine",
    "datagrip",
    "rider",
    "android studio",
    "fleet",
    "sublime_text",
    "sublime text",
    "nova",
    "textmate",
    "emacs",
    "nvim",
    "neovim",
    "macvim",
    "gvim",
    "helix",
    "lapce",
    "xcode",
    "eclipse",
    "netbeans",
    "jetbrains",
    "vim",
    // JS / TS
    "node",
    "npm",
    "pnpm",
    "yarn",
    "bun",
    "deno",
    "vite",
    "next",
    "nuxt",
    "nest",
    "webpack",
    "esbuild",
    "turbo",
    "tsc",
    "biome",
    "eslint",
    "prettier",
    "jest",
    "vitest",
    "playwright",
    "cypress",
    "prisma",
    // Python
    "python",
    "uvicorn",
    "gunicorn",
    "django",
    "flask",
    "fastapi",
    "poetry",
    "celery",
    "manage.py",
    "pipenv",
    "pyenv",
    "ruff",
    "mypy",
    "pytest",
    // Rust
    "cargo",
    "rustc",
    "rust-analyzer",
    "rustup",
    "target/debug",
    "target/release",
    // Go
    "go run",
    "gopls",
    "air",
    // JVM
    "java",
    "gradle",
    "mvn",
    "maven",
    "spring",
    // .NET
    "dotnet",
    // Ruby / PHP
    "ruby",
    "rails",
    "puma",
    "php",
    "composer",
    "artisan",
    // DB / cache / queues
    "postgres",
    "redis",
    "mongod",
    "mysql",
    "mariadb",
    "elasticsearch",
    "rabbitmq",
    "kafka",
    "minio",
    "memcached",
    "sqlite",
    // containers / k8s / local VMs
    "docker",
    "compose",
    "podman",
    "kubectl",
    "minikube",
    "kind",
    "colima",
    "orbstack",
    "nerdctl",
    // local reverse proxy / tunnels
    "nginx",
    "caddy",
    "traefik",
    "ngrok",
    "cloudflared",
    // infra / build helpers often used locally
    "terraform",
    "pulumi",
    "ansible",
    "cmake",
    "ninja",
    "watchman",
];
